# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push: # 将工作流设置为在将事件推送到 main and release/* 分支时运行
#    branches: [ "main" ]
    tags:
      - v*
#  pull_request: # 将工作流设置为在面向 main 分支的事件上运行 pull_request
#      branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository # 检出仓库
      uses: actions/checkout@v4.1.1

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies # 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyfiglet tk pyinstaller

    - name: Compile and pack # 编译打包
      run: |
        pyinstaller -F --collect-all pyfiglet GetMusic.py
        pyinstaller -F --icon=AppIcon.appiconset/512.png --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py
        ls -l dist

    - name: Archive .app files # 上传打包文件
      uses: actions/upload-artifact@v3.1.3
      with:
        name: GetMusicGUI-${{ runner.os }}
        path: dist/*

    - name: Create Release # 创建发布
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download .app files # 下载打包文件
      uses: actions/download-artifact@v3.0.2
      with:
        name: GetMusicGUI-${{ runner.os }}
        path: artifact

    - name: List files in workspace # 查看工作空间文件
      run: |
        ls -l ${{ github.workspace }}
        ls -l dist
        ls -l artifact
        mv artifact/GetMusic artifact/GetMusic-${{ runner.os }}
        mv artifact/GetMusicGUI artifact/GetMusicGUI-${{ runner.os }}
        ls -l artifact

    - name: Upload .app files to Release # 上传打包文件
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        ls -l ${{ github.workspace }}
        ls -l artifact
        tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
        gh release upload ${tag_name} artifact/*

  upload-macos:
      needs: build
      runs-on: macos-latest

      steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyfiglet tk pyinstaller

      - name: Compile and pack
        run: |
          pyinstaller -F --collect-all pyfiglet GetMusic.py
          pyinstaller -F --icon=AppIcon.appiconset/MyIcon.icns --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py
          ls -l dist

      - name: Archive .app files
        uses: actions/upload-artifact@v3.1.3
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: dist/*

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: artifact

      - name: List files in workspace
        run: |
          ls -l ${{ github.workspace }}
          ls -l dist
          ls -l artifact
          mv artifact/GetMusic artifact/GetMusic-${{ runner.os }}
          mv artifact/GetMusicGUI artifact/GetMusicGUI-${{ runner.os }}
          mv artifact/GetMusicGUI.app artifact/GetMusicGUI-${{ runner.os }}.app
          zip -r artifact/GetMusicGUI-${{ runner.os }}.zip artifact/GetMusicGUI-${{ runner.os }}.app
          rm -rf artifact/GetMusicGUI-${{ runner.os }}.app
          ls -l artifact

      - name: Upload .app files to Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ls -l ${{ github.workspace }}
          ls -l artifact
          tag_name=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          gh release upload ${tag_name} artifact/*

  upload-windows:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyfiglet tk pyinstaller

      - name: Compile and pack
        run: |
          pyinstaller -F --collect-all pyfiglet GetMusic.py
          pyinstaller -F --icon=AppIcon.appiconset/MyIco.ico --noconfirm --windowed --collect-all pyfiglet GetMusicGUI.py
          ls -l dist

      - name: Archive .app files
        uses: actions/upload-artifact@v3.1.3
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: dist/*

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: GetMusicGUI-${{ runner.os }}
          path: artifact

      - name: List files in workspace
        run: |
          ls -l ${{ github.workspace }}
          ls -l dist
          ls -l artifact
          mv artifact/GetMusic.exe artifact/GetMusic-${{ runner.os }}.exe
          mv artifact/GetMusicGUI.exe artifact/GetMusicGUI-${{ runner.os }}.exe
          ls -l artifact

      - name: Upload .app files to Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ls -l ${{ github.workspace }}
          ls -l artifact
          $tag_name = "${{ github.ref }}" -replace '^refs/tags/', ''
          echo "Tag name: $tag_name"
          gh release upload "$tag_name" .\artifact\GetMusicGUI-${{ runner.os }}.exe
          gh release upload "$tag_name" .\artifact\GetMusic-${{ runner.os }}.exe
